version: '3'
 
services:
 
    php:
        container_name: php
        build:
            context: ./docker/php
        ports:
            - 9000:9000
        volumes:
            - ${HOME}/.ssh:/root/.ssh
            - ./web/:/web/:rw
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker/drupal/:/docker/drupal
        depends_on:
            - db
        working_dir: /web/
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            SERVER_TIMEZONE: ${SERVER_TIMEZONE}
            DEVDESKTOP_DRUPAL_SETTINGS_DIR: "/docker/drupal" # In your Drupal settings file include the drupal_config.inc file from this directory in order to match the local dev environment
 
    nginx:
        container_name: nginx
        image: nginx:1.16.0-alpine
        ports:
            - 80:80
        environment:
            NGINX_HOST: ${NGINX_HOST}
            NGINX_PORT: ${NGINX_PORT}
        volumes:
            - ./web/:/web/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
 
    db:
        container_name: db
        image: mariadb:10.3.15-bionic
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql/data                        # Keep data between docker restarts (use "docker-compose down -v" to clear docker volumes including the "db_data" one)
            - ./docker/mariadb/dump:/docker-entrypoint-initdb.d  # Initialize the database from an SQL dump if the "db_data" volume is empty

volumes:
    db_data:  # Volume to store mariadb databases and keep the data between docker restarts
