# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 22, host: 22       # SSH
  config.vm.network "forwarded_port", guest: 80, host: 80       # HTTP
  config.vm.network "forwarded_port", guest: 443, host: 443     # HTTPS

  # Sync the current directory with Vagrant
  config.vm.synced_folder "./", "/home/vagrant/sources"
  # Prepare the user's SSH keys for being used by docker containers
  config.vm.synced_folder "~/.ssh", "/home/vagrant/mapped/.ssh", :mount_options => ["ro"]
  config.vm.provider "virtualbox" do |vb|
    vb.name = "projects"
    vb.gui = false
    vb.memory = "4096"
  end

  config.vm.provision :shell, :path => "vagrant-provision.sh"
  config.vm.provision :shell, :path => "vagrant-up.sh", run: 'always'

end
